---
- name: Clone daodao-notifier github repository
  become: yes
  become_user: daodao
  git:
    repo: https://{{ github_access_token }}@github.com/shifty11/dao-dao-notifier.git
    dest: /etc/daodao/dao-dao-notifier
    clone: yes
    update: yes
    force: yes

- name: Create .env file
  template:
    src: '.env.j2'
    dest: '/etc/daodao/dao-dao-notifier/.env'
    owner: root
    group: root
    mode: '644'

- name: Stop and remove previously created containers
  become_user: daodao
  shell:
    cmd: "docker-compose -f production.yml down"
    chdir: /etc/daodao/dao-dao-notifier

- name: Run containers
  become_user: daodao
  shell:
    cmd: "docker-compose -f production.yml up --build --no-deps -d --force-recreate"
    chdir: /etc/daodao/dao-dao-notifier
