---
- name: Create daodao user
  user:
    name: daodao
    comment: 'DaoDao user'
    shell: /usr/sbin/nologin
    groups: ['systemd-journal', 'adm', 'docker']
    state: present

- name: Creates daodao directory
  file:
    path: '/etc/daodao'
    state: directory
    owner: daodao
    group: daodao
    recurse: true
    mode: 0755
  changed_when: false
