version: '3.8'

services:
  db:
    image: postgres:14.5
    container_name: cosmos_notifier_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cosmos-notifier-db
    restart: unless-stopped

  db-test:
    image: postgres:14.5
    container_name: cosmos_notifier_test_db
    ports:
      - "5433:5432"
    volumes:
      - test_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cosmos-notifier-db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: cosmos_notifier_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    logging:
      driver: "none"
    volumes:
       - pgadmin:/root/.pgadmin
       - ./docker/pgadmin/local-db-servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy-dev
    container_name: cosmos_notifier_envoy
    extra_hosts:
      - "grpc:host-gateway"
    ports:
      - "8090:8090"
    volumes:
      - ./docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: unless-stopped

volumes:
  data:
    name: cosmos_notifier_data
  test_data:
    name: cosmos_notifier_test_data
  pgadmin:
    name: cosmos_notifier_pgadmin
