version: '3.9'

services:
  db-migration:
    build: go
    container_name: daodao_notifier_db_migration
    working_dir: /app
    env_file:
      - .env
    command: "/dao-dao-notifier migrate"

  nodejs:
    build: nodejs
    container_name: daodao_notifier_nodejs
    working_dir: /usr/src/app
    volumes:
      - /usr/app/node_modules
    command: npm run start
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      timeout: 10s

  telegram:
    build: go
    container_name: daodao_notifier_telegram
    working_dir: /app
    env_file:
      - .env
    command: "/dao-dao-notifier start-telegram-bot"
    depends_on:
      db-migration:
        condition: service_completed_successfully

  discord:
    build: go
    container_name: daodao_notifier_discord
    working_dir: /app
    env_file:
      - .env
    command: "/dao-dao-notifier start-discord-bot"
    depends_on:
      db-migration:
        condition: service_completed_successfully

  grpc:
    build: go
    container_name: daodao_notifier_grpc
    working_dir: /app
    env_file:
      - .env
    command: "/dao-dao-notifier grpc"
    depends_on:
      db-migration:
        condition: service_completed_successfully

  crawler:
    build: go
    container_name: daodao_notifier_crawler
    working_dir: /app
    volumes:
      - ./contracts.txt:/app/contracts.txt
      - assets:/app/assets
    env_file:
      - .env
    command: "/dao-dao-notifier crawl --repeat"
    depends_on:
      nodejs:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  envoy:
    image: envoyproxy/envoy-dev
    container_name: daodao_notifier_envoy
    volumes:
      - ./webapp/envoy.yaml:/etc/envoy/envoy.yaml

  webapp:
    env_file:
      - .env
    build:
      context: webapp
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: ${FLUTTER_CONFIG_FILE}
    container_name: daodao_notifier_webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - /var/www/daodao-notifier:/app/build/web
      - assets:/var/www/daodao-notifier/assets

volumes:
  assets:
  caddy_data: