version: '3.9'

services:
  nodejs:
    image: ghcr.io/shifty11/cosmos-notifier-nodejs:latest
    working_dir: /usr/src/app
    volumes:
      - /usr/app/node_modules
    command: npm run start
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      timeout: 10s

  telegram:
    image: ghcr.io/shifty11/cosmos-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service telegram"

  discord:
    image: ghcr.io/shifty11/cosmos-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service discord"

  grpc:
    image: ghcr.io/shifty11/cosmos-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier db migrate && /cosmos-notifier service grpc"

  contract-crawler:
    image: ghcr.io/shifty11/cosmos-notifier-go:latest
    working_dir: /app
    volumes:
      - images:/app/assets/shared
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service contract-crawler --repeat"

  chain-crawler:
    image: ghcr.io/shifty11/cosmos-notifier-go:latest
    working_dir: /app
    volumes:
      - images:/app/assets/shared
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service chain-crawler --repeat"

  validator-crawler:
    image: ghcr.io/shifty11/cosmos-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service validator-crawler --repeat"

  envoy:
    image: ghcr.io/shifty11/cosmos-notifier-envoy:latest

  webapp:
    image: ghcr.io/shifty11/cosmos-notifier-webapp:latest
    volumes:
      - images:/var/www/cosmos-notifier/assets/shared
    networks:
      - caddy
      - default

  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: cosmos-notifier.decrypto.online
        caddy.reverse_proxy: "webapp:80"

  db:
    image: postgres:14.5
    volumes:
      - /mnt/storage/swarm/cosmos-notifier/data:/var/lib/postgresql/data
    secrets:
      - cosmos-notifier-db-password-env
    environment:
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD_FILE=/run/secrets/cosmos-notifier-db-password-env
      - POSTGRES_DB=cosmosnotifier
    deploy:
      placement:
        constraints:
          - node.labels.node == data-1

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    volumes:
      - /mnt/storage/swarm/cosmos-notifier/pgbackup:/backups
    secrets:
      - cosmos-notifier-db-password-env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=cosmosnotifier
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD_FILE=/run/secrets/cosmos-notifier-db-password-env
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

  pgadmin:
    image: dpage/pgadmin4:latest
    secrets:
      - pgadmin-password
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin-password
#    logging:
#      driver: "none"
    networks:
      - caddy
      - default
    volumes:
      - pgadmin:/var/lib/pgadmin
      - /var/opt/pgbackups:/backups

  whoami-pgadmin:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: pgadmin.decrypto.online
        caddy.reverse_proxy: "pgadmin:80"

volumes:
  images:
  pgadmin:
    name: pgadmin_data

networks:
  caddy:
    external: true

secrets:
  cosmos-notifier-env:
    external: true
  cosmos-notifier-db-password-env:
    external: true
  pgadmin-password:
    external: true

