version: '3.9'

services:
  nodejs:
    image: ghcr.io/shifty11/dao-dao-notifier-nodejs:latest
    working_dir: /usr/src/app
    volumes:
      - /usr/app/node_modules
    command: npm run start
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      retries: 3
      timeout: 10s
    deploy:
      placement:
        constraints:
          - node.role != manager

  telegram:
    image: ghcr.io/shifty11/dao-dao-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service telegram"
    deploy:
      placement:
        constraints:
          - node.role != manager

  discord:
    image: ghcr.io/shifty11/dao-dao-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service discord"
    deploy:
      placement:
        constraints:
          - node.role != manager

  grpc:
    image: ghcr.io/shifty11/dao-dao-notifier-go:latest
    working_dir: /app
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier db migrate && /cosmos-notifier service grpc"
    deploy:
      placement:
        constraints:
          - node.role != manager

  contract-crawler:
    image: ghcr.io/shifty11/dao-dao-notifier-go:latest
    working_dir: /app
    volumes:
      - images:/app/assets/shared
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service contract-crawler --repeat"
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.host == daodao-notifier

  chain-crawler:
    image: ghcr.io/shifty11/dao-dao-notifier-go:latest
    working_dir: /app
    volumes:
      - images:/app/assets/shared
    secrets:
      - cosmos-notifier-env
    command: /bin/sh -c "source /run/secrets/cosmos-notifier-env && /cosmos-notifier service chain-crawler --repeat"
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.host == daodao-notifier

  envoy:
    image: ghcr.io/shifty11/dao-dao-notifier-envoy:latest
    deploy:
      placement:
        constraints:
          - node.role != manager

  webapp:
    image: ghcr.io/shifty11/dao-dao-notifier-webapp:latest
    volumes:
      - /var/www/daodao-notifier:/app/build/web
      - images:/var/www/daodao-notifier/assets/shared
    networks:
      - caddy
      - default
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.host == daodao-notifier

  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: cosmos-notifier.decrypto.online
        caddy.reverse_proxy: "webapp:80"
      placement:
        constraints:
          - node.role != manager

volumes:
  images:

networks:
  caddy:
    external: true

secrets:
  cosmos-notifier-env:
    external: true