// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/cosmos-notifier/ent/chainproposal"
	"github.com/shifty11/cosmos-notifier/ent/predicate"
)

// ChainProposalDelete is the builder for deleting a ChainProposal entity.
type ChainProposalDelete struct {
	config
	hooks    []Hook
	mutation *ChainProposalMutation
}

// Where appends a list predicates to the ChainProposalDelete builder.
func (cpd *ChainProposalDelete) Where(ps ...predicate.ChainProposal) *ChainProposalDelete {
	cpd.mutation.Where(ps...)
	return cpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cpd *ChainProposalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ChainProposalMutation](ctx, cpd.sqlExec, cpd.mutation, cpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cpd *ChainProposalDelete) ExecX(ctx context.Context) int {
	n, err := cpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cpd *ChainProposalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chainproposal.Table, sqlgraph.NewFieldSpec(chainproposal.FieldID, field.TypeInt))
	if ps := cpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cpd.mutation.done = true
	return affected, err
}

// ChainProposalDeleteOne is the builder for deleting a single ChainProposal entity.
type ChainProposalDeleteOne struct {
	cpd *ChainProposalDelete
}

// Where appends a list predicates to the ChainProposalDelete builder.
func (cpdo *ChainProposalDeleteOne) Where(ps ...predicate.ChainProposal) *ChainProposalDeleteOne {
	cpdo.cpd.mutation.Where(ps...)
	return cpdo
}

// Exec executes the deletion query.
func (cpdo *ChainProposalDeleteOne) Exec(ctx context.Context) error {
	n, err := cpdo.cpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chainproposal.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cpdo *ChainProposalDeleteOne) ExecX(ctx context.Context) {
	if err := cpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
