// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/dao-dao-notifier/ent/chain"
	"github.com/shifty11/dao-dao-notifier/ent/contract"
	"github.com/shifty11/dao-dao-notifier/ent/discordchannel"
	"github.com/shifty11/dao-dao-notifier/ent/predicate"
	"github.com/shifty11/dao-dao-notifier/ent/user"
)

// DiscordChannelQuery is the builder for querying DiscordChannel entities.
type DiscordChannelQuery struct {
	config
	limit         *int
	offset        *int
	unique        *bool
	order         []OrderFunc
	fields        []string
	predicates    []predicate.DiscordChannel
	withUsers     *UserQuery
	withContracts *ContractQuery
	withChains    *ChainQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiscordChannelQuery builder.
func (dcq *DiscordChannelQuery) Where(ps ...predicate.DiscordChannel) *DiscordChannelQuery {
	dcq.predicates = append(dcq.predicates, ps...)
	return dcq
}

// Limit adds a limit step to the query.
func (dcq *DiscordChannelQuery) Limit(limit int) *DiscordChannelQuery {
	dcq.limit = &limit
	return dcq
}

// Offset adds an offset step to the query.
func (dcq *DiscordChannelQuery) Offset(offset int) *DiscordChannelQuery {
	dcq.offset = &offset
	return dcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dcq *DiscordChannelQuery) Unique(unique bool) *DiscordChannelQuery {
	dcq.unique = &unique
	return dcq
}

// Order adds an order step to the query.
func (dcq *DiscordChannelQuery) Order(o ...OrderFunc) *DiscordChannelQuery {
	dcq.order = append(dcq.order, o...)
	return dcq
}

// QueryUsers chains the current query on the "users" edge.
func (dcq *DiscordChannelQuery) QueryUsers() *UserQuery {
	query := &UserQuery{config: dcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discordchannel.Table, discordchannel.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, discordchannel.UsersTable, discordchannel.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContracts chains the current query on the "contracts" edge.
func (dcq *DiscordChannelQuery) QueryContracts() *ContractQuery {
	query := &ContractQuery{config: dcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discordchannel.Table, discordchannel.FieldID, selector),
			sqlgraph.To(contract.Table, contract.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, discordchannel.ContractsTable, discordchannel.ContractsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChains chains the current query on the "chains" edge.
func (dcq *DiscordChannelQuery) QueryChains() *ChainQuery {
	query := &ChainQuery{config: dcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discordchannel.Table, discordchannel.FieldID, selector),
			sqlgraph.To(chain.Table, chain.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, discordchannel.ChainsTable, discordchannel.ChainsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DiscordChannel entity from the query.
// Returns a *NotFoundError when no DiscordChannel was found.
func (dcq *DiscordChannelQuery) First(ctx context.Context) (*DiscordChannel, error) {
	nodes, err := dcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{discordchannel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dcq *DiscordChannelQuery) FirstX(ctx context.Context) *DiscordChannel {
	node, err := dcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DiscordChannel ID from the query.
// Returns a *NotFoundError when no DiscordChannel ID was found.
func (dcq *DiscordChannelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{discordchannel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dcq *DiscordChannelQuery) FirstIDX(ctx context.Context) int {
	id, err := dcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DiscordChannel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DiscordChannel entity is found.
// Returns a *NotFoundError when no DiscordChannel entities are found.
func (dcq *DiscordChannelQuery) Only(ctx context.Context) (*DiscordChannel, error) {
	nodes, err := dcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{discordchannel.Label}
	default:
		return nil, &NotSingularError{discordchannel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dcq *DiscordChannelQuery) OnlyX(ctx context.Context) *DiscordChannel {
	node, err := dcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DiscordChannel ID in the query.
// Returns a *NotSingularError when more than one DiscordChannel ID is found.
// Returns a *NotFoundError when no entities are found.
func (dcq *DiscordChannelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{discordchannel.Label}
	default:
		err = &NotSingularError{discordchannel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dcq *DiscordChannelQuery) OnlyIDX(ctx context.Context) int {
	id, err := dcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DiscordChannels.
func (dcq *DiscordChannelQuery) All(ctx context.Context) ([]*DiscordChannel, error) {
	if err := dcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dcq *DiscordChannelQuery) AllX(ctx context.Context) []*DiscordChannel {
	nodes, err := dcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DiscordChannel IDs.
func (dcq *DiscordChannelQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := dcq.Select(discordchannel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dcq *DiscordChannelQuery) IDsX(ctx context.Context) []int {
	ids, err := dcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dcq *DiscordChannelQuery) Count(ctx context.Context) (int, error) {
	if err := dcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dcq *DiscordChannelQuery) CountX(ctx context.Context) int {
	count, err := dcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dcq *DiscordChannelQuery) Exist(ctx context.Context) (bool, error) {
	if err := dcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dcq *DiscordChannelQuery) ExistX(ctx context.Context) bool {
	exist, err := dcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiscordChannelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dcq *DiscordChannelQuery) Clone() *DiscordChannelQuery {
	if dcq == nil {
		return nil
	}
	return &DiscordChannelQuery{
		config:        dcq.config,
		limit:         dcq.limit,
		offset:        dcq.offset,
		order:         append([]OrderFunc{}, dcq.order...),
		predicates:    append([]predicate.DiscordChannel{}, dcq.predicates...),
		withUsers:     dcq.withUsers.Clone(),
		withContracts: dcq.withContracts.Clone(),
		withChains:    dcq.withChains.Clone(),
		// clone intermediate query.
		sql:    dcq.sql.Clone(),
		path:   dcq.path,
		unique: dcq.unique,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (dcq *DiscordChannelQuery) WithUsers(opts ...func(*UserQuery)) *DiscordChannelQuery {
	query := &UserQuery{config: dcq.config}
	for _, opt := range opts {
		opt(query)
	}
	dcq.withUsers = query
	return dcq
}

// WithContracts tells the query-builder to eager-load the nodes that are connected to
// the "contracts" edge. The optional arguments are used to configure the query builder of the edge.
func (dcq *DiscordChannelQuery) WithContracts(opts ...func(*ContractQuery)) *DiscordChannelQuery {
	query := &ContractQuery{config: dcq.config}
	for _, opt := range opts {
		opt(query)
	}
	dcq.withContracts = query
	return dcq
}

// WithChains tells the query-builder to eager-load the nodes that are connected to
// the "chains" edge. The optional arguments are used to configure the query builder of the edge.
func (dcq *DiscordChannelQuery) WithChains(opts ...func(*ChainQuery)) *DiscordChannelQuery {
	query := &ChainQuery{config: dcq.config}
	for _, opt := range opts {
		opt(query)
	}
	dcq.withChains = query
	return dcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DiscordChannel.Query().
//		GroupBy(discordchannel.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dcq *DiscordChannelQuery) GroupBy(field string, fields ...string) *DiscordChannelGroupBy {
	grbuild := &DiscordChannelGroupBy{config: dcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dcq.sqlQuery(ctx), nil
	}
	grbuild.label = discordchannel.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.DiscordChannel.Query().
//		Select(discordchannel.FieldCreateTime).
//		Scan(ctx, &v)
func (dcq *DiscordChannelQuery) Select(fields ...string) *DiscordChannelSelect {
	dcq.fields = append(dcq.fields, fields...)
	selbuild := &DiscordChannelSelect{DiscordChannelQuery: dcq}
	selbuild.label = discordchannel.Label
	selbuild.flds, selbuild.scan = &dcq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a DiscordChannelSelect configured with the given aggregations.
func (dcq *DiscordChannelQuery) Aggregate(fns ...AggregateFunc) *DiscordChannelSelect {
	return dcq.Select().Aggregate(fns...)
}

func (dcq *DiscordChannelQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dcq.fields {
		if !discordchannel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dcq.path != nil {
		prev, err := dcq.path(ctx)
		if err != nil {
			return err
		}
		dcq.sql = prev
	}
	return nil
}

func (dcq *DiscordChannelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DiscordChannel, error) {
	var (
		nodes       = []*DiscordChannel{}
		_spec       = dcq.querySpec()
		loadedTypes = [3]bool{
			dcq.withUsers != nil,
			dcq.withContracts != nil,
			dcq.withChains != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DiscordChannel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DiscordChannel{config: dcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dcq.withUsers; query != nil {
		if err := dcq.loadUsers(ctx, query, nodes,
			func(n *DiscordChannel) { n.Edges.Users = []*User{} },
			func(n *DiscordChannel, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := dcq.withContracts; query != nil {
		if err := dcq.loadContracts(ctx, query, nodes,
			func(n *DiscordChannel) { n.Edges.Contracts = []*Contract{} },
			func(n *DiscordChannel, e *Contract) { n.Edges.Contracts = append(n.Edges.Contracts, e) }); err != nil {
			return nil, err
		}
	}
	if query := dcq.withChains; query != nil {
		if err := dcq.loadChains(ctx, query, nodes,
			func(n *DiscordChannel) { n.Edges.Chains = []*Chain{} },
			func(n *DiscordChannel, e *Chain) { n.Edges.Chains = append(n.Edges.Chains, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dcq *DiscordChannelQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*DiscordChannel, init func(*DiscordChannel), assign func(*DiscordChannel, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*DiscordChannel)
	nids := make(map[int]map[*DiscordChannel]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(discordchannel.UsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(discordchannel.UsersPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(discordchannel.UsersPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(discordchannel.UsersPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*DiscordChannel]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (dcq *DiscordChannelQuery) loadContracts(ctx context.Context, query *ContractQuery, nodes []*DiscordChannel, init func(*DiscordChannel), assign func(*DiscordChannel, *Contract)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*DiscordChannel)
	nids := make(map[int]map[*DiscordChannel]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(discordchannel.ContractsTable)
		s.Join(joinT).On(s.C(contract.FieldID), joinT.C(discordchannel.ContractsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(discordchannel.ContractsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(discordchannel.ContractsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*DiscordChannel]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "contracts" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (dcq *DiscordChannelQuery) loadChains(ctx context.Context, query *ChainQuery, nodes []*DiscordChannel, init func(*DiscordChannel), assign func(*DiscordChannel, *Chain)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*DiscordChannel)
	nids := make(map[int]map[*DiscordChannel]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(discordchannel.ChainsTable)
		s.Join(joinT).On(s.C(chain.FieldID), joinT.C(discordchannel.ChainsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(discordchannel.ChainsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(discordchannel.ChainsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*DiscordChannel]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "chains" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (dcq *DiscordChannelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dcq.querySpec()
	_spec.Node.Columns = dcq.fields
	if len(dcq.fields) > 0 {
		_spec.Unique = dcq.unique != nil && *dcq.unique
	}
	return sqlgraph.CountNodes(ctx, dcq.driver, _spec)
}

func (dcq *DiscordChannelQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := dcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (dcq *DiscordChannelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   discordchannel.Table,
			Columns: discordchannel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: discordchannel.FieldID,
			},
		},
		From:   dcq.sql,
		Unique: true,
	}
	if unique := dcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordchannel.FieldID)
		for i := range fields {
			if fields[i] != discordchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dcq *DiscordChannelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dcq.driver.Dialect())
	t1 := builder.Table(discordchannel.Table)
	columns := dcq.fields
	if len(columns) == 0 {
		columns = discordchannel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dcq.sql != nil {
		selector = dcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dcq.unique != nil && *dcq.unique {
		selector.Distinct()
	}
	for _, p := range dcq.predicates {
		p(selector)
	}
	for _, p := range dcq.order {
		p(selector)
	}
	if offset := dcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DiscordChannelGroupBy is the group-by builder for DiscordChannel entities.
type DiscordChannelGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dcgb *DiscordChannelGroupBy) Aggregate(fns ...AggregateFunc) *DiscordChannelGroupBy {
	dcgb.fns = append(dcgb.fns, fns...)
	return dcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (dcgb *DiscordChannelGroupBy) Scan(ctx context.Context, v any) error {
	query, err := dcgb.path(ctx)
	if err != nil {
		return err
	}
	dcgb.sql = query
	return dcgb.sqlScan(ctx, v)
}

func (dcgb *DiscordChannelGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range dcgb.fields {
		if !discordchannel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dcgb *DiscordChannelGroupBy) sqlQuery() *sql.Selector {
	selector := dcgb.sql.Select()
	aggregation := make([]string, 0, len(dcgb.fns))
	for _, fn := range dcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dcgb.fields)+len(dcgb.fns))
		for _, f := range dcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dcgb.fields...)...)
}

// DiscordChannelSelect is the builder for selecting fields of DiscordChannel entities.
type DiscordChannelSelect struct {
	*DiscordChannelQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dcs *DiscordChannelSelect) Aggregate(fns ...AggregateFunc) *DiscordChannelSelect {
	dcs.fns = append(dcs.fns, fns...)
	return dcs
}

// Scan applies the selector query and scans the result into the given value.
func (dcs *DiscordChannelSelect) Scan(ctx context.Context, v any) error {
	if err := dcs.prepareQuery(ctx); err != nil {
		return err
	}
	dcs.sql = dcs.DiscordChannelQuery.sqlQuery(ctx)
	return dcs.sqlScan(ctx, v)
}

func (dcs *DiscordChannelSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(dcs.fns))
	for _, fn := range dcs.fns {
		aggregation = append(aggregation, fn(dcs.sql))
	}
	switch n := len(*dcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		dcs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		dcs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := dcs.sql.Query()
	if err := dcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
