// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/cosmos-notifier/ent/chain"
	"github.com/shifty11/cosmos-notifier/ent/contract"
	"github.com/shifty11/cosmos-notifier/ent/predicate"
	"github.com/shifty11/cosmos-notifier/ent/telegramchat"
	"github.com/shifty11/cosmos-notifier/ent/user"
)

// TelegramChatQuery is the builder for querying TelegramChat entities.
type TelegramChatQuery struct {
	config
	limit         *int
	offset        *int
	unique        *bool
	order         []OrderFunc
	fields        []string
	predicates    []predicate.TelegramChat
	withUsers     *UserQuery
	withContracts *ContractQuery
	withChains    *ChainQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TelegramChatQuery builder.
func (tcq *TelegramChatQuery) Where(ps ...predicate.TelegramChat) *TelegramChatQuery {
	tcq.predicates = append(tcq.predicates, ps...)
	return tcq
}

// Limit adds a limit step to the query.
func (tcq *TelegramChatQuery) Limit(limit int) *TelegramChatQuery {
	tcq.limit = &limit
	return tcq
}

// Offset adds an offset step to the query.
func (tcq *TelegramChatQuery) Offset(offset int) *TelegramChatQuery {
	tcq.offset = &offset
	return tcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tcq *TelegramChatQuery) Unique(unique bool) *TelegramChatQuery {
	tcq.unique = &unique
	return tcq
}

// Order adds an order step to the query.
func (tcq *TelegramChatQuery) Order(o ...OrderFunc) *TelegramChatQuery {
	tcq.order = append(tcq.order, o...)
	return tcq
}

// QueryUsers chains the current query on the "users" edge.
func (tcq *TelegramChatQuery) QueryUsers() *UserQuery {
	query := &UserQuery{config: tcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(telegramchat.Table, telegramchat.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, telegramchat.UsersTable, telegramchat.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContracts chains the current query on the "contracts" edge.
func (tcq *TelegramChatQuery) QueryContracts() *ContractQuery {
	query := &ContractQuery{config: tcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(telegramchat.Table, telegramchat.FieldID, selector),
			sqlgraph.To(contract.Table, contract.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, telegramchat.ContractsTable, telegramchat.ContractsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChains chains the current query on the "chains" edge.
func (tcq *TelegramChatQuery) QueryChains() *ChainQuery {
	query := &ChainQuery{config: tcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(telegramchat.Table, telegramchat.FieldID, selector),
			sqlgraph.To(chain.Table, chain.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, telegramchat.ChainsTable, telegramchat.ChainsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TelegramChat entity from the query.
// Returns a *NotFoundError when no TelegramChat was found.
func (tcq *TelegramChatQuery) First(ctx context.Context) (*TelegramChat, error) {
	nodes, err := tcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{telegramchat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tcq *TelegramChatQuery) FirstX(ctx context.Context) *TelegramChat {
	node, err := tcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TelegramChat ID from the query.
// Returns a *NotFoundError when no TelegramChat ID was found.
func (tcq *TelegramChatQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{telegramchat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tcq *TelegramChatQuery) FirstIDX(ctx context.Context) int {
	id, err := tcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TelegramChat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TelegramChat entity is found.
// Returns a *NotFoundError when no TelegramChat entities are found.
func (tcq *TelegramChatQuery) Only(ctx context.Context) (*TelegramChat, error) {
	nodes, err := tcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{telegramchat.Label}
	default:
		return nil, &NotSingularError{telegramchat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tcq *TelegramChatQuery) OnlyX(ctx context.Context) *TelegramChat {
	node, err := tcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TelegramChat ID in the query.
// Returns a *NotSingularError when more than one TelegramChat ID is found.
// Returns a *NotFoundError when no entities are found.
func (tcq *TelegramChatQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{telegramchat.Label}
	default:
		err = &NotSingularError{telegramchat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tcq *TelegramChatQuery) OnlyIDX(ctx context.Context) int {
	id, err := tcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TelegramChats.
func (tcq *TelegramChatQuery) All(ctx context.Context) ([]*TelegramChat, error) {
	if err := tcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tcq *TelegramChatQuery) AllX(ctx context.Context) []*TelegramChat {
	nodes, err := tcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TelegramChat IDs.
func (tcq *TelegramChatQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tcq.Select(telegramchat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tcq *TelegramChatQuery) IDsX(ctx context.Context) []int {
	ids, err := tcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tcq *TelegramChatQuery) Count(ctx context.Context) (int, error) {
	if err := tcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tcq *TelegramChatQuery) CountX(ctx context.Context) int {
	count, err := tcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tcq *TelegramChatQuery) Exist(ctx context.Context) (bool, error) {
	if err := tcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tcq *TelegramChatQuery) ExistX(ctx context.Context) bool {
	exist, err := tcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TelegramChatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tcq *TelegramChatQuery) Clone() *TelegramChatQuery {
	if tcq == nil {
		return nil
	}
	return &TelegramChatQuery{
		config:        tcq.config,
		limit:         tcq.limit,
		offset:        tcq.offset,
		order:         append([]OrderFunc{}, tcq.order...),
		predicates:    append([]predicate.TelegramChat{}, tcq.predicates...),
		withUsers:     tcq.withUsers.Clone(),
		withContracts: tcq.withContracts.Clone(),
		withChains:    tcq.withChains.Clone(),
		// clone intermediate query.
		sql:    tcq.sql.Clone(),
		path:   tcq.path,
		unique: tcq.unique,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TelegramChatQuery) WithUsers(opts ...func(*UserQuery)) *TelegramChatQuery {
	query := &UserQuery{config: tcq.config}
	for _, opt := range opts {
		opt(query)
	}
	tcq.withUsers = query
	return tcq
}

// WithContracts tells the query-builder to eager-load the nodes that are connected to
// the "contracts" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TelegramChatQuery) WithContracts(opts ...func(*ContractQuery)) *TelegramChatQuery {
	query := &ContractQuery{config: tcq.config}
	for _, opt := range opts {
		opt(query)
	}
	tcq.withContracts = query
	return tcq
}

// WithChains tells the query-builder to eager-load the nodes that are connected to
// the "chains" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TelegramChatQuery) WithChains(opts ...func(*ChainQuery)) *TelegramChatQuery {
	query := &ChainQuery{config: tcq.config}
	for _, opt := range opts {
		opt(query)
	}
	tcq.withChains = query
	return tcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TelegramChat.Query().
//		GroupBy(telegramchat.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tcq *TelegramChatQuery) GroupBy(field string, fields ...string) *TelegramChatGroupBy {
	grbuild := &TelegramChatGroupBy{config: tcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tcq.sqlQuery(ctx), nil
	}
	grbuild.label = telegramchat.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TelegramChat.Query().
//		Select(telegramchat.FieldCreateTime).
//		Scan(ctx, &v)
func (tcq *TelegramChatQuery) Select(fields ...string) *TelegramChatSelect {
	tcq.fields = append(tcq.fields, fields...)
	selbuild := &TelegramChatSelect{TelegramChatQuery: tcq}
	selbuild.label = telegramchat.Label
	selbuild.flds, selbuild.scan = &tcq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a TelegramChatSelect configured with the given aggregations.
func (tcq *TelegramChatQuery) Aggregate(fns ...AggregateFunc) *TelegramChatSelect {
	return tcq.Select().Aggregate(fns...)
}

func (tcq *TelegramChatQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tcq.fields {
		if !telegramchat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tcq.path != nil {
		prev, err := tcq.path(ctx)
		if err != nil {
			return err
		}
		tcq.sql = prev
	}
	return nil
}

func (tcq *TelegramChatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TelegramChat, error) {
	var (
		nodes       = []*TelegramChat{}
		_spec       = tcq.querySpec()
		loadedTypes = [3]bool{
			tcq.withUsers != nil,
			tcq.withContracts != nil,
			tcq.withChains != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TelegramChat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TelegramChat{config: tcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tcq.withUsers; query != nil {
		if err := tcq.loadUsers(ctx, query, nodes,
			func(n *TelegramChat) { n.Edges.Users = []*User{} },
			func(n *TelegramChat, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := tcq.withContracts; query != nil {
		if err := tcq.loadContracts(ctx, query, nodes,
			func(n *TelegramChat) { n.Edges.Contracts = []*Contract{} },
			func(n *TelegramChat, e *Contract) { n.Edges.Contracts = append(n.Edges.Contracts, e) }); err != nil {
			return nil, err
		}
	}
	if query := tcq.withChains; query != nil {
		if err := tcq.loadChains(ctx, query, nodes,
			func(n *TelegramChat) { n.Edges.Chains = []*Chain{} },
			func(n *TelegramChat, e *Chain) { n.Edges.Chains = append(n.Edges.Chains, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tcq *TelegramChatQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*TelegramChat, init func(*TelegramChat), assign func(*TelegramChat, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*TelegramChat)
	nids := make(map[int]map[*TelegramChat]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(telegramchat.UsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(telegramchat.UsersPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(telegramchat.UsersPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(telegramchat.UsersPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*TelegramChat]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (tcq *TelegramChatQuery) loadContracts(ctx context.Context, query *ContractQuery, nodes []*TelegramChat, init func(*TelegramChat), assign func(*TelegramChat, *Contract)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*TelegramChat)
	nids := make(map[int]map[*TelegramChat]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(telegramchat.ContractsTable)
		s.Join(joinT).On(s.C(contract.FieldID), joinT.C(telegramchat.ContractsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(telegramchat.ContractsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(telegramchat.ContractsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*TelegramChat]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "contracts" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (tcq *TelegramChatQuery) loadChains(ctx context.Context, query *ChainQuery, nodes []*TelegramChat, init func(*TelegramChat), assign func(*TelegramChat, *Chain)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*TelegramChat)
	nids := make(map[int]map[*TelegramChat]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(telegramchat.ChainsTable)
		s.Join(joinT).On(s.C(chain.FieldID), joinT.C(telegramchat.ChainsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(telegramchat.ChainsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(telegramchat.ChainsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*TelegramChat]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "chains" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (tcq *TelegramChatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tcq.querySpec()
	_spec.Node.Columns = tcq.fields
	if len(tcq.fields) > 0 {
		_spec.Unique = tcq.unique != nil && *tcq.unique
	}
	return sqlgraph.CountNodes(ctx, tcq.driver, _spec)
}

func (tcq *TelegramChatQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := tcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (tcq *TelegramChatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   telegramchat.Table,
			Columns: telegramchat.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: telegramchat.FieldID,
			},
		},
		From:   tcq.sql,
		Unique: true,
	}
	if unique := tcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramchat.FieldID)
		for i := range fields {
			if fields[i] != telegramchat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tcq *TelegramChatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tcq.driver.Dialect())
	t1 := builder.Table(telegramchat.Table)
	columns := tcq.fields
	if len(columns) == 0 {
		columns = telegramchat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tcq.sql != nil {
		selector = tcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tcq.unique != nil && *tcq.unique {
		selector.Distinct()
	}
	for _, p := range tcq.predicates {
		p(selector)
	}
	for _, p := range tcq.order {
		p(selector)
	}
	if offset := tcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TelegramChatGroupBy is the group-by builder for TelegramChat entities.
type TelegramChatGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcgb *TelegramChatGroupBy) Aggregate(fns ...AggregateFunc) *TelegramChatGroupBy {
	tcgb.fns = append(tcgb.fns, fns...)
	return tcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tcgb *TelegramChatGroupBy) Scan(ctx context.Context, v any) error {
	query, err := tcgb.path(ctx)
	if err != nil {
		return err
	}
	tcgb.sql = query
	return tcgb.sqlScan(ctx, v)
}

func (tcgb *TelegramChatGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range tcgb.fields {
		if !telegramchat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tcgb *TelegramChatGroupBy) sqlQuery() *sql.Selector {
	selector := tcgb.sql.Select()
	aggregation := make([]string, 0, len(tcgb.fns))
	for _, fn := range tcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tcgb.fields)+len(tcgb.fns))
		for _, f := range tcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tcgb.fields...)...)
}

// TelegramChatSelect is the builder for selecting fields of TelegramChat entities.
type TelegramChatSelect struct {
	*TelegramChatQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcs *TelegramChatSelect) Aggregate(fns ...AggregateFunc) *TelegramChatSelect {
	tcs.fns = append(tcs.fns, fns...)
	return tcs
}

// Scan applies the selector query and scans the result into the given value.
func (tcs *TelegramChatSelect) Scan(ctx context.Context, v any) error {
	if err := tcs.prepareQuery(ctx); err != nil {
		return err
	}
	tcs.sql = tcs.TelegramChatQuery.sqlQuery(ctx)
	return tcs.sqlScan(ctx, v)
}

func (tcs *TelegramChatSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(tcs.fns))
	for _, fn := range tcs.fns {
		aggregation = append(aggregation, fn(tcs.sql))
	}
	switch n := len(*tcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		tcs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		tcs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := tcs.sql.Query()
	if err := tcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
