// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/cosmos-notifier/ent/addresstracker"
	"github.com/shifty11/cosmos-notifier/ent/chain"
	"github.com/shifty11/cosmos-notifier/ent/discordchannel"
	"github.com/shifty11/cosmos-notifier/ent/predicate"
	"github.com/shifty11/cosmos-notifier/ent/telegramchat"
	"github.com/shifty11/cosmos-notifier/ent/validator"
)

// ValidatorQuery is the builder for querying Validator entities.
type ValidatorQuery struct {
	config
	ctx                 *QueryContext
	order               []OrderFunc
	inters              []Interceptor
	predicates          []predicate.Validator
	withChain           *ChainQuery
	withAddressTrackers *AddressTrackerQuery
	withTelegramChats   *TelegramChatQuery
	withDiscordChannels *DiscordChannelQuery
	withFKs             bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ValidatorQuery builder.
func (vq *ValidatorQuery) Where(ps ...predicate.Validator) *ValidatorQuery {
	vq.predicates = append(vq.predicates, ps...)
	return vq
}

// Limit the number of records to be returned by this query.
func (vq *ValidatorQuery) Limit(limit int) *ValidatorQuery {
	vq.ctx.Limit = &limit
	return vq
}

// Offset to start from.
func (vq *ValidatorQuery) Offset(offset int) *ValidatorQuery {
	vq.ctx.Offset = &offset
	return vq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vq *ValidatorQuery) Unique(unique bool) *ValidatorQuery {
	vq.ctx.Unique = &unique
	return vq
}

// Order specifies how the records should be ordered.
func (vq *ValidatorQuery) Order(o ...OrderFunc) *ValidatorQuery {
	vq.order = append(vq.order, o...)
	return vq
}

// QueryChain chains the current query on the "chain" edge.
func (vq *ValidatorQuery) QueryChain() *ChainQuery {
	query := (&ChainClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(validator.Table, validator.FieldID, selector),
			sqlgraph.To(chain.Table, chain.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, validator.ChainTable, validator.ChainColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAddressTrackers chains the current query on the "address_trackers" edge.
func (vq *ValidatorQuery) QueryAddressTrackers() *AddressTrackerQuery {
	query := (&AddressTrackerClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(validator.Table, validator.FieldID, selector),
			sqlgraph.To(addresstracker.Table, addresstracker.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, validator.AddressTrackersTable, validator.AddressTrackersColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTelegramChats chains the current query on the "telegram_chats" edge.
func (vq *ValidatorQuery) QueryTelegramChats() *TelegramChatQuery {
	query := (&TelegramChatClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(validator.Table, validator.FieldID, selector),
			sqlgraph.To(telegramchat.Table, telegramchat.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, validator.TelegramChatsTable, validator.TelegramChatsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDiscordChannels chains the current query on the "discord_channels" edge.
func (vq *ValidatorQuery) QueryDiscordChannels() *DiscordChannelQuery {
	query := (&DiscordChannelClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(validator.Table, validator.FieldID, selector),
			sqlgraph.To(discordchannel.Table, discordchannel.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, validator.DiscordChannelsTable, validator.DiscordChannelsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Validator entity from the query.
// Returns a *NotFoundError when no Validator was found.
func (vq *ValidatorQuery) First(ctx context.Context) (*Validator, error) {
	nodes, err := vq.Limit(1).All(setContextOp(ctx, vq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{validator.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vq *ValidatorQuery) FirstX(ctx context.Context) *Validator {
	node, err := vq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Validator ID from the query.
// Returns a *NotFoundError when no Validator ID was found.
func (vq *ValidatorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(1).IDs(setContextOp(ctx, vq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{validator.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vq *ValidatorQuery) FirstIDX(ctx context.Context) int {
	id, err := vq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Validator entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Validator entity is found.
// Returns a *NotFoundError when no Validator entities are found.
func (vq *ValidatorQuery) Only(ctx context.Context) (*Validator, error) {
	nodes, err := vq.Limit(2).All(setContextOp(ctx, vq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{validator.Label}
	default:
		return nil, &NotSingularError{validator.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vq *ValidatorQuery) OnlyX(ctx context.Context) *Validator {
	node, err := vq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Validator ID in the query.
// Returns a *NotSingularError when more than one Validator ID is found.
// Returns a *NotFoundError when no entities are found.
func (vq *ValidatorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(2).IDs(setContextOp(ctx, vq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{validator.Label}
	default:
		err = &NotSingularError{validator.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vq *ValidatorQuery) OnlyIDX(ctx context.Context) int {
	id, err := vq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Validators.
func (vq *ValidatorQuery) All(ctx context.Context) ([]*Validator, error) {
	ctx = setContextOp(ctx, vq.ctx, "All")
	if err := vq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Validator, *ValidatorQuery]()
	return withInterceptors[[]*Validator](ctx, vq, qr, vq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vq *ValidatorQuery) AllX(ctx context.Context) []*Validator {
	nodes, err := vq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Validator IDs.
func (vq *ValidatorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vq.ctx.Unique == nil && vq.path != nil {
		vq.Unique(true)
	}
	ctx = setContextOp(ctx, vq.ctx, "IDs")
	if err = vq.Select(validator.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vq *ValidatorQuery) IDsX(ctx context.Context) []int {
	ids, err := vq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vq *ValidatorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vq.ctx, "Count")
	if err := vq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vq, querierCount[*ValidatorQuery](), vq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vq *ValidatorQuery) CountX(ctx context.Context) int {
	count, err := vq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vq *ValidatorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vq.ctx, "Exist")
	switch _, err := vq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vq *ValidatorQuery) ExistX(ctx context.Context) bool {
	exist, err := vq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ValidatorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vq *ValidatorQuery) Clone() *ValidatorQuery {
	if vq == nil {
		return nil
	}
	return &ValidatorQuery{
		config:              vq.config,
		ctx:                 vq.ctx.Clone(),
		order:               append([]OrderFunc{}, vq.order...),
		inters:              append([]Interceptor{}, vq.inters...),
		predicates:          append([]predicate.Validator{}, vq.predicates...),
		withChain:           vq.withChain.Clone(),
		withAddressTrackers: vq.withAddressTrackers.Clone(),
		withTelegramChats:   vq.withTelegramChats.Clone(),
		withDiscordChannels: vq.withDiscordChannels.Clone(),
		// clone intermediate query.
		sql:  vq.sql.Clone(),
		path: vq.path,
	}
}

// WithChain tells the query-builder to eager-load the nodes that are connected to
// the "chain" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *ValidatorQuery) WithChain(opts ...func(*ChainQuery)) *ValidatorQuery {
	query := (&ChainClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withChain = query
	return vq
}

// WithAddressTrackers tells the query-builder to eager-load the nodes that are connected to
// the "address_trackers" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *ValidatorQuery) WithAddressTrackers(opts ...func(*AddressTrackerQuery)) *ValidatorQuery {
	query := (&AddressTrackerClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withAddressTrackers = query
	return vq
}

// WithTelegramChats tells the query-builder to eager-load the nodes that are connected to
// the "telegram_chats" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *ValidatorQuery) WithTelegramChats(opts ...func(*TelegramChatQuery)) *ValidatorQuery {
	query := (&TelegramChatClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withTelegramChats = query
	return vq
}

// WithDiscordChannels tells the query-builder to eager-load the nodes that are connected to
// the "discord_channels" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *ValidatorQuery) WithDiscordChannels(opts ...func(*DiscordChannelQuery)) *ValidatorQuery {
	query := (&DiscordChannelClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withDiscordChannels = query
	return vq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Validator.Query().
//		GroupBy(validator.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vq *ValidatorQuery) GroupBy(field string, fields ...string) *ValidatorGroupBy {
	vq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ValidatorGroupBy{build: vq}
	grbuild.flds = &vq.ctx.Fields
	grbuild.label = validator.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Validator.Query().
//		Select(validator.FieldCreateTime).
//		Scan(ctx, &v)
func (vq *ValidatorQuery) Select(fields ...string) *ValidatorSelect {
	vq.ctx.Fields = append(vq.ctx.Fields, fields...)
	sbuild := &ValidatorSelect{ValidatorQuery: vq}
	sbuild.label = validator.Label
	sbuild.flds, sbuild.scan = &vq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ValidatorSelect configured with the given aggregations.
func (vq *ValidatorQuery) Aggregate(fns ...AggregateFunc) *ValidatorSelect {
	return vq.Select().Aggregate(fns...)
}

func (vq *ValidatorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vq); err != nil {
				return err
			}
		}
	}
	for _, f := range vq.ctx.Fields {
		if !validator.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vq.path != nil {
		prev, err := vq.path(ctx)
		if err != nil {
			return err
		}
		vq.sql = prev
	}
	return nil
}

func (vq *ValidatorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Validator, error) {
	var (
		nodes       = []*Validator{}
		withFKs     = vq.withFKs
		_spec       = vq.querySpec()
		loadedTypes = [4]bool{
			vq.withChain != nil,
			vq.withAddressTrackers != nil,
			vq.withTelegramChats != nil,
			vq.withDiscordChannels != nil,
		}
	)
	if vq.withChain != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, validator.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Validator).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Validator{config: vq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vq.withChain; query != nil {
		if err := vq.loadChain(ctx, query, nodes, nil,
			func(n *Validator, e *Chain) { n.Edges.Chain = e }); err != nil {
			return nil, err
		}
	}
	if query := vq.withAddressTrackers; query != nil {
		if err := vq.loadAddressTrackers(ctx, query, nodes,
			func(n *Validator) { n.Edges.AddressTrackers = []*AddressTracker{} },
			func(n *Validator, e *AddressTracker) { n.Edges.AddressTrackers = append(n.Edges.AddressTrackers, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withTelegramChats; query != nil {
		if err := vq.loadTelegramChats(ctx, query, nodes,
			func(n *Validator) { n.Edges.TelegramChats = []*TelegramChat{} },
			func(n *Validator, e *TelegramChat) { n.Edges.TelegramChats = append(n.Edges.TelegramChats, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withDiscordChannels; query != nil {
		if err := vq.loadDiscordChannels(ctx, query, nodes,
			func(n *Validator) { n.Edges.DiscordChannels = []*DiscordChannel{} },
			func(n *Validator, e *DiscordChannel) { n.Edges.DiscordChannels = append(n.Edges.DiscordChannels, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vq *ValidatorQuery) loadChain(ctx context.Context, query *ChainQuery, nodes []*Validator, init func(*Validator), assign func(*Validator, *Chain)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Validator)
	for i := range nodes {
		if nodes[i].chain_validators == nil {
			continue
		}
		fk := *nodes[i].chain_validators
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chain.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chain_validators" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (vq *ValidatorQuery) loadAddressTrackers(ctx context.Context, query *AddressTrackerQuery, nodes []*Validator, init func(*Validator), assign func(*Validator, *AddressTracker)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Validator)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AddressTracker(func(s *sql.Selector) {
		s.Where(sql.InValues(validator.AddressTrackersColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.validator_address_trackers
		if fk == nil {
			return fmt.Errorf(`foreign-key "validator_address_trackers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "validator_address_trackers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (vq *ValidatorQuery) loadTelegramChats(ctx context.Context, query *TelegramChatQuery, nodes []*Validator, init func(*Validator), assign func(*Validator, *TelegramChat)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Validator)
	nids := make(map[int]map[*Validator]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(validator.TelegramChatsTable)
		s.Join(joinT).On(s.C(telegramchat.FieldID), joinT.C(validator.TelegramChatsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(validator.TelegramChatsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(validator.TelegramChatsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Validator]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*TelegramChat](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "telegram_chats" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (vq *ValidatorQuery) loadDiscordChannels(ctx context.Context, query *DiscordChannelQuery, nodes []*Validator, init func(*Validator), assign func(*Validator, *DiscordChannel)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Validator)
	nids := make(map[int]map[*Validator]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(validator.DiscordChannelsTable)
		s.Join(joinT).On(s.C(discordchannel.FieldID), joinT.C(validator.DiscordChannelsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(validator.DiscordChannelsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(validator.DiscordChannelsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Validator]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*DiscordChannel](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "discord_channels" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (vq *ValidatorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vq.querySpec()
	_spec.Node.Columns = vq.ctx.Fields
	if len(vq.ctx.Fields) > 0 {
		_spec.Unique = vq.ctx.Unique != nil && *vq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vq.driver, _spec)
}

func (vq *ValidatorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(validator.Table, validator.Columns, sqlgraph.NewFieldSpec(validator.FieldID, field.TypeInt))
	_spec.From = vq.sql
	if unique := vq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vq.path != nil {
		_spec.Unique = true
	}
	if fields := vq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, validator.FieldID)
		for i := range fields {
			if fields[i] != validator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vq *ValidatorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vq.driver.Dialect())
	t1 := builder.Table(validator.Table)
	columns := vq.ctx.Fields
	if len(columns) == 0 {
		columns = validator.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vq.sql != nil {
		selector = vq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vq.ctx.Unique != nil && *vq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vq.predicates {
		p(selector)
	}
	for _, p := range vq.order {
		p(selector)
	}
	if offset := vq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ValidatorGroupBy is the group-by builder for Validator entities.
type ValidatorGroupBy struct {
	selector
	build *ValidatorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vgb *ValidatorGroupBy) Aggregate(fns ...AggregateFunc) *ValidatorGroupBy {
	vgb.fns = append(vgb.fns, fns...)
	return vgb
}

// Scan applies the selector query and scans the result into the given value.
func (vgb *ValidatorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vgb.build.ctx, "GroupBy")
	if err := vgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ValidatorQuery, *ValidatorGroupBy](ctx, vgb.build, vgb, vgb.build.inters, v)
}

func (vgb *ValidatorGroupBy) sqlScan(ctx context.Context, root *ValidatorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vgb.fns))
	for _, fn := range vgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vgb.flds)+len(vgb.fns))
		for _, f := range *vgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ValidatorSelect is the builder for selecting fields of Validator entities.
type ValidatorSelect struct {
	*ValidatorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vs *ValidatorSelect) Aggregate(fns ...AggregateFunc) *ValidatorSelect {
	vs.fns = append(vs.fns, fns...)
	return vs
}

// Scan applies the selector query and scans the result into the given value.
func (vs *ValidatorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vs.ctx, "Select")
	if err := vs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ValidatorQuery, *ValidatorSelect](ctx, vs.ValidatorQuery, vs, vs.inters, v)
}

func (vs *ValidatorSelect) sqlScan(ctx context.Context, root *ValidatorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vs.fns))
	for _, fn := range vs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
