-- modify "chains" table
ALTER TABLE "chains" ALTER COLUMN "bech32_prefix" DROP DEFAULT;
-- create "validators" table
CREATE TABLE "validators" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "address" character varying NOT NULL, "moniker" character varying NOT NULL, "chain_validators" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "validators_chains_validators" FOREIGN KEY ("chain_validators") REFERENCES "chains" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create index "validator_address" to table: "validators"
CREATE INDEX "validator_address" ON "validators" ("address");
-- create index "validator_moniker" to table: "validators"
CREATE INDEX "validator_moniker" ON "validators" ("moniker");
-- drop index "addresstracker_address_chain_a_3e2f36cdcb6f4a3f04a660254f75606e" from table: "address_trackers"
DROP INDEX "addresstracker_address_chain_a_3e2f36cdcb6f4a3f04a660254f75606e";
-- modify "address_trackers" table
ALTER TABLE "address_trackers" ADD COLUMN "validator_address_trackers" bigint NULL, ADD CONSTRAINT "address_trackers_validators_address_trackers" FOREIGN KEY ("validator_address_trackers") REFERENCES "validators" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create index "addresstracker_address_chain_a_3e2f36cdcb6f4a3f04a660254f75606e" to table: "address_trackers"
CREATE INDEX "addresstracker_address_chain_a_3e2f36cdcb6f4a3f04a660254f75606e" ON "address_trackers" ("address", "chain_address_trackers", "discord_channel_address_trackers", "telegram_chat_address_trackers");
