// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AddressTracker is the predicate function for addresstracker builders.
type AddressTracker func(*sql.Selector)

// Chain is the predicate function for chain builders.
type Chain func(*sql.Selector)

// ChainProposal is the predicate function for chainproposal builders.
type ChainProposal func(*sql.Selector)

// Contract is the predicate function for contract builders.
type Contract func(*sql.Selector)

// ContractProposal is the predicate function for contractproposal builders.
type ContractProposal func(*sql.Selector)

// DiscordChannel is the predicate function for discordchannel builders.
type DiscordChannel func(*sql.Selector)

// TelegramChat is the predicate function for telegramchat builders.
type TelegramChat func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Validator is the predicate function for validator builders.
type Validator func(*sql.Selector)
