// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contract is the predicate function for contract builders.
type Contract func(*sql.Selector)

// DiscordChannel is the predicate function for discordchannel builders.
type DiscordChannel func(*sql.Selector)

// Proposal is the predicate function for proposal builders.
type Proposal func(*sql.Selector)

// TelegramChat is the predicate function for telegramchat builders.
type TelegramChat func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
