// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: admin_service.proto

package admin_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastMessageRequest_MessageType int32

const (
	BroadcastMessageRequest_TELEGRAM_TEST BroadcastMessageRequest_MessageType = 0
	BroadcastMessageRequest_DISCORD_TEST  BroadcastMessageRequest_MessageType = 1
	BroadcastMessageRequest_TELEGRAM      BroadcastMessageRequest_MessageType = 2
	BroadcastMessageRequest_DISCORD       BroadcastMessageRequest_MessageType = 3
)

// Enum value maps for BroadcastMessageRequest_MessageType.
var (
	BroadcastMessageRequest_MessageType_name = map[int32]string{
		0: "TELEGRAM_TEST",
		1: "DISCORD_TEST",
		2: "TELEGRAM",
		3: "DISCORD",
	}
	BroadcastMessageRequest_MessageType_value = map[string]int32{
		"TELEGRAM_TEST": 0,
		"DISCORD_TEST":  1,
		"TELEGRAM":      2,
		"DISCORD":       3,
	}
)

func (x BroadcastMessageRequest_MessageType) Enum() *BroadcastMessageRequest_MessageType {
	p := new(BroadcastMessageRequest_MessageType)
	*p = x
	return p
}

func (x BroadcastMessageRequest_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BroadcastMessageRequest_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_service_proto_enumTypes[0].Descriptor()
}

func (BroadcastMessageRequest_MessageType) Type() protoreflect.EnumType {
	return &file_admin_service_proto_enumTypes[0]
}

func (x BroadcastMessageRequest_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BroadcastMessageRequest_MessageType.Descriptor instead.
func (BroadcastMessageRequest_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0, 0}
}

type BroadcastMessageResponse_Status int32

const (
	BroadcastMessageResponse_SENDING BroadcastMessageResponse_Status = 0
	BroadcastMessageResponse_SENT    BroadcastMessageResponse_Status = 1
	BroadcastMessageResponse_FAILED  BroadcastMessageResponse_Status = 3
)

// Enum value maps for BroadcastMessageResponse_Status.
var (
	BroadcastMessageResponse_Status_name = map[int32]string{
		0: "SENDING",
		1: "SENT",
		3: "FAILED",
	}
	BroadcastMessageResponse_Status_value = map[string]int32{
		"SENDING": 0,
		"SENT":    1,
		"FAILED":  3,
	}
)

func (x BroadcastMessageResponse_Status) Enum() *BroadcastMessageResponse_Status {
	p := new(BroadcastMessageResponse_Status)
	*p = x
	return p
}

func (x BroadcastMessageResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BroadcastMessageResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_service_proto_enumTypes[1].Descriptor()
}

func (BroadcastMessageResponse_Status) Type() protoreflect.EnumType {
	return &file_admin_service_proto_enumTypes[1]
}

func (x BroadcastMessageResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BroadcastMessageResponse_Status.Descriptor instead.
func (BroadcastMessageResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{1, 0}
}

type BroadcastMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                              `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type    BroadcastMessageRequest_MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=daodao_notifier_grpc.BroadcastMessageRequest_MessageType" json:"type,omitempty"`
}

func (x *BroadcastMessageRequest) Reset() {
	*x = BroadcastMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessageRequest) ProtoMessage() {}

func (x *BroadcastMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessageRequest.ProtoReflect.Descriptor instead.
func (*BroadcastMessageRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BroadcastMessageRequest) GetType() BroadcastMessageRequest_MessageType {
	if x != nil {
		return x.Type
	}
	return BroadcastMessageRequest_TELEGRAM_TEST
}

type BroadcastMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   BroadcastMessageResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=daodao_notifier_grpc.BroadcastMessageResponse_Status" json:"status,omitempty"`
	Response string                          `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *BroadcastMessageResponse) Reset() {
	*x = BroadcastMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessageResponse) ProtoMessage() {}

func (x *BroadcastMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessageResponse.ProtoReflect.Descriptor instead.
func (*BroadcastMessageResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastMessageResponse) GetStatus() BroadcastMessageResponse_Status {
	if x != nil {
		return x.Status
	}
	return BroadcastMessageResponse_SENDING
}

func (x *BroadcastMessageResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_admin_service_proto protoreflect.FileDescriptor

var file_admin_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x64, 0x61, 0x6f, 0x64, 0x61, 0x6f, 0x5f, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0xd1, 0x01, 0x0a, 0x17,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x4d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x39, 0x2e, 0x64, 0x61, 0x6f, 0x64, 0x61, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x4d, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x11, 0x0a, 0x0d, 0x54, 0x45, 0x4c, 0x45, 0x47, 0x52, 0x41, 0x4d, 0x5f, 0x54, 0x45, 0x53, 0x54,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x45,
	0x53, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x45, 0x4c, 0x45, 0x47, 0x52, 0x41, 0x4d,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x03, 0x22,
	0xb2, 0x01, 0x0a, 0x18, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x64,
	0x61, 0x6f, 0x64, 0x61, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x03, 0x32, 0x85, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x2e, 0x64, 0x61, 0x6f, 0x64,
	0x61, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x64, 0x61, 0x6f, 0x64, 0x61,
	0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10,
	0x67, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_service_proto_rawDescOnce sync.Once
	file_admin_service_proto_rawDescData = file_admin_service_proto_rawDesc
)

func file_admin_service_proto_rawDescGZIP() []byte {
	file_admin_service_proto_rawDescOnce.Do(func() {
		file_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_service_proto_rawDescData)
	})
	return file_admin_service_proto_rawDescData
}

var file_admin_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_service_proto_goTypes = []interface{}{
	(BroadcastMessageRequest_MessageType)(0), // 0: daodao_notifier_grpc.BroadcastMessageRequest.MessageType
	(BroadcastMessageResponse_Status)(0),     // 1: daodao_notifier_grpc.BroadcastMessageResponse.Status
	(*BroadcastMessageRequest)(nil),          // 2: daodao_notifier_grpc.BroadcastMessageRequest
	(*BroadcastMessageResponse)(nil),         // 3: daodao_notifier_grpc.BroadcastMessageResponse
}
var file_admin_service_proto_depIdxs = []int32{
	0, // 0: daodao_notifier_grpc.BroadcastMessageRequest.type:type_name -> daodao_notifier_grpc.BroadcastMessageRequest.MessageType
	1, // 1: daodao_notifier_grpc.BroadcastMessageResponse.status:type_name -> daodao_notifier_grpc.BroadcastMessageResponse.Status
	2, // 2: daodao_notifier_grpc.AdminService.BroadcastMessage:input_type -> daodao_notifier_grpc.BroadcastMessageRequest
	3, // 3: daodao_notifier_grpc.AdminService.BroadcastMessage:output_type -> daodao_notifier_grpc.BroadcastMessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_service_proto_init() }
func file_admin_service_proto_init() {
	if File_admin_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_service_proto_goTypes,
		DependencyIndexes: file_admin_service_proto_depIdxs,
		EnumInfos:         file_admin_service_proto_enumTypes,
		MessageInfos:      file_admin_service_proto_msgTypes,
	}.Build()
	File_admin_service_proto = out.File
	file_admin_service_proto_rawDesc = nil
	file_admin_service_proto_goTypes = nil
	file_admin_service_proto_depIdxs = nil
}
